### ISSUE TITLE
Po usunięciu ankiety z dashboard znikają raporty

### ISSUE THREAD

**Issue by rpiotrowski** [ankieter-gui/engine#71]
po dodaniu ankiety, raporty się pojawiają

**Comment by kiryk** [comment]
Problem był powodowany przez ankiety z błędami. Teraz problemy są wykrywane i błędy nie robią szkód.

Błąd powodowany przez nie nie był krytyczny, ale mylił interfejs i prowadził do nie wyświetlania się niczego w menu głównym.
