### ISSUE TITLE
Endpoint do zmiany źródła danych

### ISSUE THREAD

**Issue by emilekm2142** [ankieter-gui/engine#76]
Zależne od: https://github.com/ankieter-gui/engine/issues/78

Endpoint do zmiany źródła danych i walidacja że można to zrobić. 
+ jak nie można to niech wskaże które wykresy moga byc odrzucone

**Comment by kiryk** [comment]
Wystarczy rozszerzyć API o możliwości nie tylko tworzenia nowych zbiorów danych, ale też nadpisywania ich.

Mamy już `/api/data/new` ale nie mamy `/api/data/<id>`, które mogłoby działać z metodą POST.
Istnieją już analogiczne pary endpointów, np. `/api/report/new` i `/api/report/<id>`, więc nowe rozwiązanie powinno działać podobnie do nich.

**Comment by kiryk** [comment]
Podmieniając dane na nowe, trzeba sprawdzać, czy mają one taką samą strukturę, jaką mają poprzednie dane.

Kiedy dane są wrzucane po raz pierwszy, to nie trzeba przeprowadzać takiego testu.

**Comment by kiryk** [comment]
https://github.com/ankieter-gui/engine/commit/37db358ef049506efebeb1e4d636c123eafa4ef5

Dane można podmieniać w ten sam sposób, w który się je wrzuca, tj. przez `/api/data/new/<id>`.
