### ISSUE TITLE
Możliwość pobierania czegokolwiek

### ISSUE THREAD

**Issue by kiryk** [ankieter-gui/engine#79]
Zależne od: https://github.com/ankieter-gui/engine/issues/78

Powinno dać się pobrać z powrotem:
- XMLe ankiet,
- dane z ankiet (CSV przekonwertowane z DB)
- JSONy raportów,

Idealnie gdyby nowy raport dało się utworzyć z istniejącego już JSONa przez upload.

**Comment by rpiotrowski** [comment]
2300751974a6b8d03f91968c6a4522581da19408
b77b785f6bf50e0d2202c6736fcd55170d8ae870
9f6d9397d25fc1cc2a361ef85c46a70ecfe1740c

**Comment by kiryk** [comment]
Trzeba tylko sprawdzić czy endpointy są zgodne z polityką uprawnień i nazewnictwem

**Comment by kiryk** [comment]
Trzeba zrobić kilka zmian

W uprawnieniach:
1. Dane zebrane w ankiecie może pobrać tylko owner ankiety.
2. Raport i ankietę (bez danych) może pobrać owner, editor i reader.

W nazwach endpointów:
1. `/api/report/<int:report_id>/download` jest całkowicie OK
2. `/api/survey/<int:survey_id>/download/csv` na `/api/data/<int:survey_id>/download`.
3. `/api/survey/<int:survey_id>/download/xml` na `/api/survey/<int:survey_id>/download`.

W działaniu endpointa:
1. Dane pobierane z `/api/data/<int:survey_id>/download` muszą być plikiem CSV reprezentującym bazę danych z `data/*.db`.

**Comment by rpiotrowski** [comment]
2c3d1153a104447e036124c8a6626f866291e7a0
